package plugin

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"enumscan/internal/models"
	"enumscan/internal/scope"
	"enumscan/internal/store"
)

func setupTestStore(t *testing.T) *store.SQLiteCLI {
	t.Helper()
	dir := t.TempDir()
	db, err := store.OpenSQLiteCLI(filepath.Join(dir, "test.sqlite"))
	if err != nil {
		t.Fatalf("OpenSQLiteCLI: %v", err)
	}
	if err := db.Migrate(context.Background()); err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	return db
}

func TestManifestValidation(t *testing.T) {
	manifestContent := `
name: test_plugin
version: 1.0.0
author: tester
description: Test plugin
type: lua
exec: /tmp/test.lua
permissions:
  - network
  - store_write
subscriptions:
  - port.open
`
	dir := t.TempDir()
	manifestPath := filepath.Join(dir, "plugin.yaml")
	if err := os.WriteFile(manifestPath, []byte(manifestContent), 0644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	m, err := LoadManifest(manifestPath)
	if err != nil {
		t.Fatalf("LoadManifest: %v", err)
	}
	if m.Name != "test_plugin" || m.Type != "lua" {
		t.Errorf("unexpected manifest content: %+v", m)
	}

	invalidContent := `
name: bad_plugin
type: invalid_type
`
	badPath := filepath.Join(dir, "bad.yaml")
	_ = os.WriteFile(badPath, []byte(invalidContent), 0644)
	if _, err := LoadManifest(badPath); err == nil {
		t.Errorf("expected error loading invalid manifest")
	}
}

func TestPermissionGuard(t *testing.T) {
	guard := NewPermissionGuard([]string{"network", "store_read"})

	if err := guard.Check("network"); err != nil {
		t.Errorf("expected network permission granted")
	}
	if err := guard.Check("store_write"); err == nil {
		t.Errorf("expected store_write permission denied")
	}
}

func TestLuaRunner(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("admin panel exposed"))
	}))
	defer ts.Close()

	dir := t.TempDir()
	scriptPath := filepath.Join(dir, "test.lua")
	scriptContent := `
local res = http_get(event.target)
if res then
    add_finding("Exposed Admin Panel")
end
`
	if err := os.WriteFile(scriptPath, []byte(scriptContent), 0644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	m := &PluginManifest{
		Name:          "test_lua",
		Version:       "1.0.0",
		Type:          "lua",
		Exec:          scriptPath,
		Permissions:   []string{"network", "store_write"},
		Subscriptions: []string{"port.open"},
	}

	runner := NewLuaRunner(m)
	evt := models.Event{ScanID: "scan-lua", Type: "port.open", Target: ts.URL}
	res, err := runner.Execute(context.Background(), evt)
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}

	if len(res.Findings) == 0 {
		t.Errorf("expected finding generated by Lua script runner")
	}
}

func TestPluginManager(t *testing.T) {
	db := setupTestStore(t)
	guard := scope.New([]string{"127.0.0.1", "localhost", "127.0.0.1:0"})

	dir := t.TempDir()
	scriptPath := filepath.Join(dir, "test.lua")
	_ = os.WriteFile(scriptPath, []byte("http_get(event.target)\nadd_finding()"), 0644)

	m := &PluginManifest{
		Name:          "test_mgr",
		Version:       "1.0.0",
		Type:          "lua",
		Exec:          scriptPath,
		Permissions:   []string{"network", "store_write"},
		Subscriptions: []string{"port.open"},
	}

	pm, err := NewManager(db, guard, "")
	if err != nil {
		t.Fatalf("NewManager: %v", err)
	}
	pm.RegisterPlugin(m)

	if pm.Name() != "plugin_sdk" {
		t.Errorf("expected module name 'plugin_sdk'")
	}
	if len(pm.Subscriptions()) == 0 {
		t.Errorf("expected subscriptions registered")
	}
}
